CREATE TABLE IF NOT EXISTS appliances (
  id SERIAL PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  isOn BOOLEAN DEFAULT FALSE,
  power INTEGER DEFAULT 0,
  amount NUMERIC(10, 2) DEFAULT 0.00,
  current NUMERIC(10, 2) DEFAULT 0.00,
  voltage NUMERIC(10, 2) DEFAULT 220.00
);
